# -*- coding: utf-8 -*-
"""01_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6KifpFKryUQrqPFAWwI0fhkzKUO20uB
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

mh_df = pd.read_csv('/content/Mental_Health_Dataset/mental_health_dataset.csv')
mh_df.head(5)

# Inspecting the dataset
#
print(mh_df.shape)
mh_df.info()

"""## **Observations of the Data Inspection**

> - The dataset has a total of 10,000 row entries with 14 different variables
>
> - No missing values were observed
>
> - The data types for all columns were in their correct format.

"""

# Check for duplicate rows
mh_df.duplicated().sum()

# Summary statistics for all variables
#
mh_df.describe(include='all')

"""## **Observations of the Summary Statistics**

> Check for Outliers:
> -   The mean value of all *continuous variables* (age, stress_level, sleep_hours, physical_activity_days, depression_score, anxiety_score, social_support_score, and productivity_score) in the dataset was approximately equal to the median, hence indicating **a symmetric/ normally distributed data**.
>
> -  No apparent outliers were observed based on the minimum, maximum, interquartile range, and standard deviation. The values appear to fall within a reasonable range, suggesting consistency across the dataset.
>
> - Summary statistics across the dataset reveal that most variables in the dataset demonstrate high variability (CV > 50%), as evidenced by their standard deviation values relative to their respective means, while a few exhibit moderate to low variation.



"""

# Visualise Outliers using Box plot for all number variables

# Selecting the numerical columns
selected_cols = ['age', 'stress_level', 'sleep_hours', 'physical_activity_days', 'depression_score', 'anxiety_score', 'social_support_score', 'productivity_score']
melted_df = mh_df[selected_cols].melt(var_name='Variable', value_name='Value')

# Plotting it
plt.figure(figsize=(15, 8))
sns.boxplot(x='Variable', y='Value', data=melted_df)
plt.title("Boxplots for Multiple Variables")
plt.savefig('boxplot_for_multiple_variables.png')
plt.show()

# Encoding the ordinal values in the "mental_health_risk" variable with numbers for future spearman correlation analysis

# The mapping defined
risk_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
mh_df['mental_health_risk_encoded'] = mh_df['mental_health_risk'].map(risk_mapping)
mh_df.to_csv('encoded_dataset.csv', index=False)
print(mh_df[['mental_health_risk', 'mental_health_risk_encoded']].head(10))



